from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER
import io

def generate_session_report(session_title, messages):
    """Generates a professional PDF report from a list of chat messages."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        'MainTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=HexColor('#6366f1'), # Brand Indigo
        alignment=TA_CENTER,
        spaceAfter=20
    )
    
    bubble_user = ParagraphStyle(
        'UserMessage',
        parent=styles['Normal'],
        fontSize=10,
        textColor=HexColor('#374151'),
        leftIndent=20,
        spaceBefore=10
    )
    
    bubble_ai = ParagraphStyle(
        'AssistantMessage',
        parent=styles['Normal'],
        fontSize=10,
        textColor=HexColor('#1f2937'),
        backgroundColor=HexColor('#f3f4f6'),
        borderPadding=5,
        spaceBefore=15,
        spaceAfter=15
    )

    content = []
    
    # Header
    content.append(Paragraph("AI Document Intelligence Report", title_style))
    content.append(Paragraph(f"Session: {session_title or 'Research Session'}", styles['Heading2']))
    content.append(Spacer(1, 12))
    
    # Body
    for msg in messages:
        role = msg.get("role", "user")
        text = msg.get("content", "")
        
        if role == "user":
            content.append(Paragraph(f"<b>Question:</b> {text}", bubble_user))
        else:
            content.append(Paragraph(f"<b>Researcher Insight:</b> {text}", bubble_ai))
            
            # Sources if available
            sources = msg.get("sources", [])
            if sources:
                source_text = "<i>Sources: " + ", ".join(list(set([s['metadata']['source'] for s in sources]))) + "</i>"
                content.append(Paragraph(source_text, styles['Italic']))
        
        content.append(Spacer(1, 10))

    # Footer
    content.append(Spacer(1, 50))
    content.append(Paragraph("Generated by AIDoc Intel - Project Researcher Laboratory", styles['Caption']))

    doc.build(content)
    buffer.seek(0)
    return buffer
